### ISSUE TITLE
结构体学习一下typedef的形式，以及指针结构体的调用，完成demo

### ISSUE THREAD

**Issue by roboticszeng** [Augive2613/C-Program-Demo#1]
例：

```
typedef struct
{

    _iq k[2];
    _iq output[2];

} filter_typedef;

_iq filter_update(filter_typedef *handle, _iq input)
{

    handle->output[1] = handle->output[0];
    handle->output[0] = _IQmpy(handle->k[0], input) + _IQmpy(handle->k[1], handle->output[1]);

    return handle->output[0];
}
```

**Comment by Augive2613** [comment]
#include <stdio.h>
typedef struct
{
    double score;
    int age;
} stu;
typedef struct
{
    double a;
    int b;
} note;
int main()
{
    stu s = {78.5, 22};
    note c = {0, 0};
    stu *p;
    note *q;
    p = &s;
    q->a = p->score;
    q->b = p->age;
    printf("%f %d", q->a, q->b);
}
